/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iesvirgendelcarmen.lmsgi;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author antonio
 */
public class JFrameXML extends javax.swing.JFrame {

    /**
     * Creates new form JFrameXML
     */
    public JFrameXML() {
        initComponents();
        // setLookAndFeel("javax.swing.plat.metal.MetalLookAndFeel");

        /*filter = new FileNameExtensionFilter("XML file", "xml", "XML");
        jFileChooserXML.addChoosableFileFilter(filter);
        jFileChooserXML.setFileFilter(filter);
        // añadimos otro filtro (para archivos HTML)
        filter = new FileNameExtensionFilter("HTML file", "html", "htm");
        jFileChooserXML.addChoosableFileFilter(filter); */
        filterXML = new FileNameExtensionFilter("XML file", "xml", "XML");
        jFileChooserXML.addChoosableFileFilter(filterXML);

        filterHTML = new FileNameExtensionFilter("HTML file", "html", "htm");
        jFileChooserXML.addChoosableFileFilter(filterHTML);

        filterDTD = new FileNameExtensionFilter("DTD file", "dtd", "DTD");
        jFileChooserXML.addChoosableFileFilter(filterDTD);

        filterXSD = new FileNameExtensionFilter("XSD file", "xsd", "XSD");
        jFileChooserXML.addChoosableFileFilter(filterXSD);

        filterXSL = new FileNameExtensionFilter("XSL file", "xsl", "XSLT");
        jFileChooserXML.addChoosableFileFilter(filterXSL);

        filterXQ = new FileNameExtensionFilter("xQuery", "xq", "XQ");
        jFileChooserXML.addChoosableFileFilter(filterXQ);
        
        jTextFieldXPath.addActionListener(l -> {
            if(!jTextFieldXPath.getText().isEmpty()) {
                jTextAreaResultadoXPath.setText(controller.xPathEvaluate(jTextFieldXPath.getText()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserXML = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaXML1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDTD = new javax.swing.JTextArea();
        jButtonCargarDTD = new javax.swing.JButton();
        jButtonCargarXML = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaXML3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaXSD = new javax.swing.JTextArea();
        jButtonLimpiar2 = new javax.swing.JButton();
        jButtonCargarXML3 = new javax.swing.JButton();
        jButtonCargarXSD = new javax.swing.JButton();
        jButtonValidar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldXPath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaXML = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResultadoXPath = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCargarXML2 = new javax.swing.JButton();
        jButtonCargarXSLT = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaXML2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaXSLT = new javax.swing.JTextArea();
        jButtonHTMLsalida = new javax.swing.JButton();
        jButtonEjecutar = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaXML1.setColumns(20);
        jTextAreaXML1.setRows(5);
        jScrollPane3.setViewportView(jTextAreaXML1);

        jTextAreaDTD.setColumns(20);
        jTextAreaDTD.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDTD);

        jButtonCargarDTD.setText("Cargar DTD");
        jButtonCargarDTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDTDActionPerformed(evt);
            }
        });

        jButtonCargarXML.setText("Cargar XML");
        jButtonCargarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarXMLActionPerformed(evt);
            }
        });

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCargarDTD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCargarXML, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCargarXML)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCargarDTD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpiar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(417, 417, 417))
        );

        jTabbedPane1.addTab("Validar DTD", jPanel1);

        jTextAreaXML3.setColumns(20);
        jTextAreaXML3.setRows(5);
        jScrollPane5.setViewportView(jTextAreaXML3);

        jTextAreaXSD.setColumns(20);
        jTextAreaXSD.setRows(5);
        jScrollPane6.setViewportView(jTextAreaXSD);

        jButtonLimpiar2.setText("Limpiar");
        jButtonLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiar2ActionPerformed(evt);
            }
        });

        jButtonCargarXML3.setText("Cargar XML");
        jButtonCargarXML3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarXML3ActionPerformed(evt);
            }
        });

        jButtonCargarXSD.setText("Cargar XSD");
        jButtonCargarXSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarXSDActionPerformed(evt);
            }
        });

        jButtonValidar1.setText("Validar");
        jButtonValidar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLimpiar2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jButtonCargarXML3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCargarXSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jButtonValidar1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCargarXML3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCargarXSD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonValidar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiar2)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Validar XSD", jPanel2);

        jTextFieldXPath.setText("Expresión XPath");
        jTextFieldXPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXPathActionPerformed(evt);
            }
        });

        jTextAreaXML.setEditable(false);
        jTextAreaXML.setColumns(20);
        jTextAreaXML.setRows(5);
        jScrollPane1.setViewportView(jTextAreaXML);

        jTextAreaResultadoXPath.setEditable(false);
        jTextAreaResultadoXPath.setColumns(20);
        jTextAreaResultadoXPath.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResultadoXPath);

        jButton1.setText("Evaluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cargar XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jTextFieldXPath, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldXPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("xPath", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        //jTabbedPane1.addTab("xQuery", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        //jTabbedPane1.addTab("About...", jPanel6);

        jButtonCargarXML2.setText("Cargar XML");
        jButtonCargarXML2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarXML2ActionPerformed(evt);
            }
        });

        jButtonCargarXSLT.setText("Cargar XSLT");
        jButtonCargarXSLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarXSLTActionPerformed(evt);
            }
        });

        jTextAreaXML2.setColumns(20);
        jTextAreaXML2.setRows(5);
        jScrollPane7.setViewportView(jTextAreaXML2);

        jTextAreaXSLT.setColumns(20);
        jTextAreaXSLT.setRows(5);
        jScrollPane8.setViewportView(jTextAreaXSLT);

        jButtonHTMLsalida.setText("HTML salida");
        jButtonHTMLsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHTMLsalidaActionPerformed(evt);
            }
        });

        jButtonEjecutar.setText("Ejecutar");
        jButtonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjecutarActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane9.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonHTMLsalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEjecutar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCargarXML2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonCargarXSLT)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCargarXML2)
                    .addComponent(jButtonCargarXSLT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEjecutar)
                    .addComponent(jButtonHTMLsalida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("XSLT", jPanel4);

        jMenuFile.setText("File");
        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBar1.add(jMenuEdit);

        jMenuHelp.setText("Help");
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextFieldXPath.setText("");
        jTextAreaResultadoXPath.setText("");
        jTextAreaXML.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldXPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXPathActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldXPathActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFileChooserXML.setFileFilter(filterXML); // ESTO ES LO QUE SE VA CAMBIANDO SEGÚN LO QUE QUERAMOS

        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            // log.append("Opening: " + file.getName() + "." + newline);

            // PROBAMOS A VER SI FUNCIONA: ABRIR UN ARCHIVO Y EN EL TEXT AREA QUE SAQUE EL NOMBRE DEL ARCHIVO
            // jTextAreaXML.setText(file.getName());
            // AHORA EL ARCHIVO CARGARLO EN UN STRING Y LO METEMOS EN EL TEXT AREA
            // jTextAreaXML.setText("Cargando archvo:\n"+file.getName());
            // CARGAMOS EN EL TEXT AREA EL CONTENIDO DEL ARCHIVO
            try {
                jTextAreaXML.setText(
                        new String(Files.readAllBytes(file.toPath())));
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFile(file);
                }
                
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
            /* USANDO SCANNER
            String contenido = "";
            try {    
                Scanner sc = new Scanner(file);
                while(sc.hasNextLine()) {
                    contenido += sc.nextLine();
                    contenido += "\n";
                }
                jTextAreaXML.setText(contenido);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            } */

        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // tengo que ponerle de nombre "boton VALIDAR XML" en la pestaña "validar DTD"
        
        // vamos a "Validar" a través del Controller
        jTextAreaDTD.setText(controller.validateDTD());
        
        
        
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiar2ActionPerformed
        // TODO add your handling code here:
        jTextAreaXML3.setText("");
        jTextAreaXSD.setText("");
    }//GEN-LAST:event_jButtonLimpiar2ActionPerformed

    private void jButtonCargarXML2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarXML2ActionPerformed
        jFileChooserXML.setFileFilter(filterXML);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();         
            try {
                jTextAreaXML2.setText(
                        new String(Files.readAllBytes(file.toPath())));
                // jLabel9.setText(file.getName());
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFile(file);  // AQUI CREO QUE ES setFileXML ?????????????
                }
                
                
                /* COPIADO DE JUANGU. CREO QUE VA EN EL BOTON "Cargar XSLT"
                if(controller != null) controller.setFileXSL(file);
                else {
                    controller= new Controller(file);
                } 
                
                } catch(IOException ex) {
                
                }    
                
                } else {
                
                }
                
                */
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());         
    }//GEN-LAST:event_jButtonCargarXML2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // llamamos a la función evaluar
        // nos aseguramos primero que no sea vacío (que haya texto)
        if(!jTextFieldXPath.getText().isEmpty()) {
            jTextAreaResultadoXPath.setText(controller.xPathEvaluate(jTextFieldXPath.getText()));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCargarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarXMLActionPerformed
        jFileChooserXML.setFileFilter(filterXML); // ESTO ES LO QUE SE VA CAMBIANDO SEGÚN LO QUE QUERAMOS

        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            // log.append("Opening: " + file.getName() + "." + newline);

            try {
                jTextAreaXML1.setText(
                        new String(Files.readAllBytes(file.toPath())));
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFile(file);
                }           
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());
    }//GEN-LAST:event_jButtonCargarXMLActionPerformed

    private void jButtonCargarDTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDTDActionPerformed
        jFileChooserXML.setFileFilter(filterDTD); // ESTO ES LO QUE SE VA CAMBIANDO SEGÚN LO QUE QUERAMOS

        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            // log.append("Opening: " + file.getName() + "." + newline);

            try {
                jTextAreaDTD.setText(
                        new String(Files.readAllBytes(file.toPath())));
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFile(file);
                }           
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());
    }//GEN-LAST:event_jButtonCargarDTDActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextAreaDTD.setText("");
        jTextAreaXML1.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCargarXSLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarXSLTActionPerformed
        jFileChooserXML.setFileFilter(filterXSL);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();         
            try {
                jTextAreaXSLT.setText(
                        new String(Files.readAllBytes(file.toPath())));
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFileXSL(file);
                }
                
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());
    }//GEN-LAST:event_jButtonCargarXSLTActionPerformed

    private void jButtonCargarXSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarXSDActionPerformed
        jFileChooserXML.setFileFilter(filterXSD);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();         
            try {
                jTextAreaXSD.setText(
                        new String(Files.readAllBytes(file.toPath())));
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFile(file);
                }
                
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());
    }//GEN-LAST:event_jButtonCargarXSDActionPerformed

    private void jButtonCargarXML3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarXML3ActionPerformed
    jFileChooserXML.setFileFilter(filterXML);
        int returnVal = jFileChooserXML.showOpenDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();         
            try {
                jTextAreaXML3.setText(
                        new String(Files.readAllBytes(file.toPath())));
                if(controller == null) {
                    controller = new Controller(file);      
                } else {
                    controller.setFile(file);
                }
                
            } catch (IOException ex) {
                Logger.getLogger(JFrameXML.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength()); 
    }//GEN-LAST:event_jButtonCargarXML3ActionPerformed

    private void jButtonHTMLsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHTMLsalidaActionPerformed
        jFileChooserXML.setFileFilter(filterHTML);
        int returnVal = jFileChooserXML.showSaveDialog(JFrameXML.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserXML.getSelectedFile();
            if (controller == null) {
                controller = new Controller(file);
            } else {
                
                controller.setFileHTML(file);
            }
        } else {
            // log.append("Open command cancelled by user." + newline); 
        }
        // log.setCaretPosition(log.getDocument().getLength());
    }//GEN-LAST:event_jButtonHTMLsalidaActionPerformed

    private void jButtonValidar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidar1ActionPerformed
        jTextAreaXSD.setText(controller.validateXSD());
    }//GEN-LAST:event_jButtonValidar1ActionPerformed

    private void jButtonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjecutarActionPerformed
        if (controller.save2XML(jTextAreaXML2.getText())
                && controller.save2XSL(jTextAreaXSLT.getText())) {
           jTextArea3.setText(controller.xslTransform());
        } else {
            jTextArea3.setText("Error al guardar los archivos");
        } 
    }//GEN-LAST:event_jButtonEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameXML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCargarDTD;
    private javax.swing.JButton jButtonCargarXML;
    private javax.swing.JButton jButtonCargarXML2;
    private javax.swing.JButton jButtonCargarXML3;
    private javax.swing.JButton jButtonCargarXSD;
    private javax.swing.JButton jButtonCargarXSLT;
    private javax.swing.JButton jButtonEjecutar;
    private javax.swing.JButton jButtonHTMLsalida;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiar2;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JButton jButtonValidar1;
    private javax.swing.JFileChooser jFileChooserXML;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextAreaDTD;
    private javax.swing.JTextArea jTextAreaResultadoXPath;
    private javax.swing.JTextArea jTextAreaXML;
    private javax.swing.JTextArea jTextAreaXML1;
    private javax.swing.JTextArea jTextAreaXML2;
    private javax.swing.JTextArea jTextAreaXML3;
    private javax.swing.JTextArea jTextAreaXSD;
    private javax.swing.JTextArea jTextAreaXSLT;
    private javax.swing.JTextField jTextFieldXPath;
    // End of variables declaration//GEN-END:variables

    private FileFilter filterXML, filterHTML, filterDTD, filterXSD, filterXSL, filterXQ;
    
    private Controller controller;
}
